#pragma once

typedef
enum HFW_NET_FW_PROTOCOLS
{
	IP_PROTOCOL_ICMP4 = 1,
	IP_PROTOCOL_TCP = 6,
	IP_PROTOCOL_UDP = 17,
	IP_PROTOCOL_ICMP6 = 58
} HFW_NET_FW_PROTOCOLS;

typedef
enum HFW_NET_FW_UDP_LOCAL_PORT
{
	EDGE_TRAVERSAL = 3666,
	PLAY_TO_DISCOVERY = 3702,
} HFW_NET_FW_UDP_LOCAL_PORT;

typedef
enum HFW_NET_FW_TCP_LOCAL_PORT
{
	RPC_ENDPOINT_MAPPER = 135,
	IPHTTPS = 443,
	RPC_DYNAMIC_PORTS = 1024 // 1024 - 5000
} HFW_NET_FW_TCP_LOCAL_PORT;